name: Release Workspace

on:
  workflow_call:

jobs:
  deploy-testnet:
    runs-on: "ubuntu-latest"

    environment: contract-testnet
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: |
            projects/typescript-examples/package-lock.json

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install algokit
        run: pipx install algokit

      - name: Bootstrap dependencies
        run: algokit project bootstrap all

      - name: Deploy to testnet
        run: algokit deploy testnet
        env:
          # This is the account that becomes the creator of the contract
          DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
          # The dispenser account is used to ensure the deployer account is funded
          DISPENSER_MNEMONIC: ${{ secrets.DISPENSER_MNEMONIC }}
